version: '2'
linters:
  default: all
  disable:
    - cyclop
    - exhaustruct
    - forcetypeassert
    - funlen
    - gocognit
    - gocyclo
    - godot
    - godox
    - ireturn
    - lll
    - maintidx
    - mnd
    - nestif
    - nonamedreturns
    - tagliatelle
    - varnamelen
    - wsl
  settings:
    depguard:
      rules:
        regexp:
          files:
            - '!**/internal/cachedregexp/**'
            - '!**/main_test.go'
          deny:
            - pkg: regexp
              desc:
                Use github.com/g-rath/osv-detector/internal/cachedregexp instead
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - err113
          - goconst
        path: _test\.go
      - linters:
          - gochecknoglobals
        path: main.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
