version: '2'
linters:
  default: all
  # prettier-ignore
  disable:
    - cyclop          #
    - exhaustruct     # overkill
    - forcetypeassert # too hard
    - funcorder       #
    - funlen          #
    - gocognit        #
    - gocyclo         #
    - godot           # comments are fine without full stops
    - godox           # to-do comments are fine
    - ireturn         # disagree with, sort of
    - lll             #
    - maintidx        #
    - mnd             # not every number is magic
    - nestif          #
    - nonamedreturns  # they have their uses
    - tagliatelle     # we're parsing data from external sources
    - varnamelen      # maybe later
    - wsl             # disagree with, for now
  settings:
    depguard:
      rules:
        regexp:
          files:
            - '!**/internal/cachedregexp/**'
            - '!**/main_test.go'
          deny:
            - pkg: regexp
              desc:
                Use github.com/g-rath/osv-detector/internal/cachedregexp instead
    staticcheck:
      checks:
        - all
        - -QF1006 # lift into loop condition
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - err113
          - goconst
        path: _test\.go
      - linters:
          - gochecknoglobals
        path: main.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
