output:
  sort-results: true
linters:
  enable-all: true
  disable:
    - cyclop
    - exhaustruct      # overkill
    - forcetypeassert  # too hard
    - funlen
    - gocognit
    - gocyclo
    - godot            # comments are fine without full stops
    - godox            # to-do comments are fine
    - maintidx
    - gofumpt
    - ireturn          # disagree with, sort of
    - lll              # line length is hard
    - mnd              # not every number is magic
    - nestif
    - nonamedreturns   # they have their uses
    - tagliatelle      # we're parsing data from external sources
    - tenv             # Deprecated
    - varnamelen       # maybe later
    - wsl              # disagree with, for now
    - intrange
    - copyloopvar
    - predeclared
    - govet

linters-settings:
  depguard:
    rules:
      regexp:
        files:
          - '!**/internal/cachedregexp/**'
          - '!**/main_test.go'
        deny:
          - pkg: 'regexp'
            desc:
              'Use github.com/g-rath/osv-detector/internal/cachedregexp instead'

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - goconst
        - goerr113
        - dupl
    - path: main.go
      linters:
        - gochecknoglobals
